spring:
  datasource:
    url: jdbc:h2:~/os-assign;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            format_sql: true
            use_sql_comments: true
    show-sql: true


